### ISSUE TITLE
depguard does not check for "fmt"

### ISSUE THREAD

**Issue by kokizzu** [OpenPeeDeeP/depguard#18]
golangci.yml config:
```
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/rs/zerolog
      - fmt
```
example go file:
```
package main

import "fmt"

func main() {
  fmt.Println("test")
}
```
example run `golangci-lint run *.go`

Expected result: error
Current result: no error
