### ISSUE TITLE
Intermittent incorrect "`xyz` is in the denylist" errors

### ISSUE THREAD

**Issue by bmhatfield** [OpenPeeDeeP/depguard#25]
Hi there,

We're using `depguard` as part of `golangci-lint` (v1.47.3). We've been getting intermittent false positives - given the same code and same rules, re-running multiple times will produce different results. Each of the false positives do not match any of our actual rules (of which we have 3). The false positives themselves change - they don't seem to be centered around any particular package in our repository. True positives (ie, a rule that has legitimately been broken) seem reliable.

I haven't been able to track down if any particular condition seems to cause this false positive behavior. Clearing the go and golangci-lint caches doesn't seem to influence the behavior. It seems to have become more prevalent on more recent versions of Go, especially since 1.18 but increasing in 1.19. It occurs both locally (MacOS) and in CI (CircleCI, Alpine Linux container).

I'm painfully aware that this issue description is light on technical detail, because I haven't been able to diagnose this issue so far. I've been delaying filing it for some time because of this, but nobody else seems to have filed this as an issue, so I thought I would at least start the conversation. Is anyone else seeing this?

**Comment by bmhatfield** [comment]
It looks like [this issue](https://github.com/OpenPeeDeeP/depguard/issues/24) mentions the itermittent denylisting in the body, however, we are not observing the NPEs discussed in that issue.

**Comment by ldez** [comment]
hello @bmhatfield, I'm interested in a reproducible use case, have you something to share?

**Comment by jerome-laforge** [comment]
> Is anyone else seeing this?

I am facing with the same issue. And as @bmhatfield, this issue is more prevalent with Go 1.19 on my local machine (Linux) and in our CI (on-premise gitlab).

**Comment by bmhatfield** [comment]
> hello @bmhatfield, I'm interested in a reproducible use case, have you something to share?

Here's an example snippet of our config, though I imagine anything would do this. Because this is intermittent / random, I don't really have a reliable reproduce case beyond `golangci-lint`, `go 1.19`, and _maybe_ linux-based containers.

```
linters-settings:
  depguard:
    list-type: denylist
    packages:
      - log
      - "github.com/gogo/protobuf"
    packages-with-error-message:
      - log: "Use shared/logger"
      - github.com/gogo/protobuf: "Use golang/protobuf"
    include-go-root: true
```
